version: '3.7'
services:
    db:
        image: mysql:5.7
        restart: always
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/mysql
    app:
        build: ./devstacks/dockerfiles/php
        depends_on:
            - db
        env_file:
            - .env
        volumes:
            - .:/app:cached
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        depends_on:
            - app
        volumes:
            - ./devstacks/dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/app/public:cached

volumes:
    db_data:
