version: '3.7'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: dev
            MYSQL_USER: db_user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
    app:
        build: ./devstacks/dockerfiles/php
        restart: always
        depends_on:
            - db
        volumes:
            - .:/app:cached
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - 80:80
        depends_on:
            - app
        volumes:
            - ./devstacks/dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/app/public:cached
    node:
        image: node:10-alpine
        restart: always
        ports:
            - 8080:8080
        volumes:
            - .:/app:cached
        working_dir: /app
        command: ['npm', 'run', 'dev-server']

volumes:
    db_data:
